### PR TITLE
Model cleanup

### PR DESCRIPTION
**Pull request by Akodiat**
Sorted out some of the issues, but please have a look if you still find any oddities.
I've added a basic test suit (at http://localhost:8080/test, or whatever port you are using), so feel free to extend that.

### CODE REVIEW

**Comment by Akodiat** [comment]
I still have to make sure all old .oxview files can load and fix the base clicking on drag issue, so don't merge just yet. But hopefully, the editing bugs should be gone now.

**Review by m-matthies — APPROVED** [review]
All tests i can think of seem to work, I believe its stable to merge.

**Review by m-matthies — CHANGES_REQUESTED** [review]
- delete function is broken for box select 
- strand selection does not work for scaffold [10k_DNA structure] (occurs after box select \ delete fails)

**Comment by Akodiat** [comment]
I've made some updates, but it is still not ready for merge since, while it looks visually correct, strands are not properly deleted.

**Comment by Akodiat** [comment]
Everything seems to be deleted properly now

**Comment by Akodiat** [comment]
Everything seems to be deleted properly now

**Comment by Akodiat** [comment]
Oops, didn't mean to close the pull request. I think it is ready for merge now

**Pull request merged**
