### PR TITLE
Increase the compatibility with .mgl files

### PR DESCRIPTION
**Pull request by lorenzo-rovigatti**
This PR adds support for cylinders, simple spheres and "group" objects to oxview, as well as makes it possible to use colors with 4 components (where the latter one controls the opacity).
This PR also includes changes to the `dist` folder. Is this OK?

### CODE REVIEW

**Comment by Akodiat** [comment]
I haven't looked at it in detail, but all those changed js files in the `dist` directory should have no need to update. My guess is that you are using an old (or at least different) version of the typescript compiler with some different conventions. If I compile your code, I also get a lot of changes in `dist`, which I assume is my compiler trying to change everything back. `tsc --version` gives me 4.9.5, not sure what Erik and Michael use.

Could you remove all dist changes except `file_reading.js`?

**Comment by lorenzo-rovigatti** [comment]
Thanks for feedback Joakim! I'm also using 4.9.5, so that's a bit puzzling. Also, note that my previous PR (which was merged a few days ago) did not contain any js file, so I suspect that at least some of the changes you are seeing are due to those commits. I'll try to clean up the PR regardless, and in the meantime let's see if Michael or Erik have any input about this!

**Comment by lorenzo-rovigatti** [comment]
I have rebased the branch so that the only file changed is `file_reading.ts`. Let me know if you want to compile & commit the result yourself or if I do it!

**Comment by Akodiat** [comment]
Hi Lorenzo,

I'm sorry for not getting back to you earlier, but I'm on vacation. It looks much better now, so feel free to squash and merge it.

**Review by Akodiat — APPROVED** [review]
👍

**Comment by lorenzo-rovigatti** [comment]
Thank you Joakim! I guess only @ErikPoppleton and @zoombya can squash&merge? Or should I squash the commits myself first?

**Comment by m-matthies** [comment]
Thx guys!

**Comment by lorenzo-rovigatti** [comment]
Thanks @zoombya ! Note that no `.js` file has been committed, so maybe you'll have to somehow compile the code and commit the result yourself? How does it work? Should I also commit the compiled js files?

**Comment by m-matthies** [comment]
Hm it still did quite a bunch of things to the js files. But first glance they should not affect anything.
Let's do our regular hot testing.

**Comment by lorenzo-rovigatti** [comment]
Not really. If you look [here](https://github.com/sulcgroup/oxdna-viewer/pull/112/files) you'll see that the only file with changes is `file_reading.ts`

**Comment by m-matthies** [comment]
Maybe they changed smth in the transpiler?... 
These are from the current commit log.. 
image

**Comment by lorenzo-rovigatti** [comment]
Well that answers my question: you do the compiling and commit the result :-)
Yes, I think that `tsc` is doing something funky, since as @Akodiat and I noticed, my commits resulted in a lot of changes to unrelated js files. I don't know what's happening here, but the changes look rather inoffensive

**Comment by m-matthies** [comment]
Point taken 👍 , I basically saw the pull request changing 29 files and realized I don't have the time to look at it.
Move's this Monday, so have no time for living. But hence Joakim also had a look at it -> should be fine.

**Pull request merged**
